### PR TITLE
Update youtube_channel_info.txt

### PR DESCRIPTION
**Pull request by mhsagor103**
Added "Nexus TV HD"!
https://youtube.com/@NexusTelevisionLive

### CODE REVIEW

**Comment by mhsagor103** [comment]
Though ATN News Live Stream is working in this link, "https://youtube.com/@atnnewsltd/live", The following m3u8 file is not getting updated "https://github.com/gift4bd/ytm/blob/main/ATNNews.m3u8".

Can you kindly check the issue?

**Review by gift4bd — APPROVED** [review]

**Comment by gift4bd** [comment]
> Though ATN News Live Stream is working in this link, "https://youtube.com/@atnnewsltd/live", The following m3u8 file is not getting updated "https://github.com/gift4bd/ytm/blob/main/ATNNews.m3u8".
> 
> Can you kindly check the issue?

Updated...thanks for bringing the issue to me!

**Review by gift4bd — COMMENTED** [review]
Inbox me on telegram @mnu_kst

**Comment by gift4bd** [comment]
Send request me to update channels or links if needed.

**Pull request closed without merging**
